<div className='cgu-container'>
  <h1>Aide aux particuliers</h1>

  <h3>Que dois-je faire si on me demande d’effectuer une tâche que je refuse ?</h3>
  <p>L’immersion est une prestation de service qui ne s’analyse ni comme une prestation de travail, ni comme un stage. Cela signifie notamment qu’il n’existe aucun lien de subordination entre le professionnel et le testeur. Il vous appartient de respecter les règles de l’entreprise en ce compris ses codes, sa culture, ses horaires et les éventuels équipements. Si le professionnel vous demande d’effectuer une tâche cela n’est pas pour vous donner un ordre quelconque mais pour vous permettre d’apprécier le plus concrètement possible son activité professionnelle. Si cette tâche venait à vous déplaire, il suffira de le lui dire avec la délicatesse requise.</p>

  <h3>Que dois-je faire si l’on me propose une rémunération et/ou des pourboires ?</h3>
  <p>L’immersion est une prestation de service qui ne s’analyse ni comme une prestation de travail, ni comme un stage. Cela signifie notamment que le testeur ne peut prétendre à aucune rémunération, ni à aucune gratification sous quelle qu’en soit la forme. Il vous appartient donc de refuser toute rémunération et tout pourboire qui pourrait vous être proposé durant votre immersion.</p>

  <h3>Que dois-je faire si je suis victime d’un accident ou si je cause un dommage durant l’immersion ?</h3>
  <p>Avant de débuter une immersion, il vous appartient de vous assurer que votre état de santé est en adéquation avec le lieu et/ou avec l’activité professionnelle du professionnel. Il convient notamment de vérifier que vos vaccins sont à jour. En cas de doute, il vous appartient de prendre contact avec votre médecin traitant. Avant de débuter une immersion, vous avez l’obligation de transmettre à la société METROBOULODODO une attestation d’assurance et de responsabilité civile couvrant les dommages dont vous pourriez être l’auteur ou la victime durant la période d’immersion. En cas d’accident, il vous appartient d’en informer le professionnel et votre compagnie d’assurances dans les meilleurs délais afin que celle-ci prenne en charge vos préjudices ou les préjudices que vous avez causés.</p>

  <h3>Que se passe-t-il si je tombe malade ?</h3>
  <p>Conformément aux stipulations de l’article 5.1 des Conditions Générales d’Utilisation, lorsque l’interruption de l’immersion est faite pour des motifs non imputables au professionnel, le testeur ne peut prétendre à aucun remboursement du prix de l’immersion. Si votre état de santé ne vous permet pas d’effectuer l’immersion, il vous appartient d’en informer le professionnel et la société MetroBouloDodo par écrit exclusivement. Si votre état de santé ne vous permet pas de continuer l’immersion, il vous appartient d’en informer le professionnel. Les jours d’immersion non effectuées pour cause de maladie ne sont susceptibles d’aucun report sauf accord avec le professionnel.</p>

  <h3>Est-ce que je peux réutiliser les informations acquises durant l’immersion ?</h3>
  <p>En effectuant une immersion vous vous engagez à respecter les exigences de confidentialité fixées par le professionnel. Vous ne devez donc pas faire usage des informations acquises durant l’immersion afin de les transmettre à un concurrent ou à un tiers. De manière générale, l’immersion ne doit avoir ni pour objet ni pour effet de nuire, directement ou non, aux intérêts du professionnel.</p>

  <h3>Que dois-je faire si l’immersion ne se déroule pas dans de bonnes conditions ?</h3>
  <p>L’immersion est une prestation de service qui ne s’analyse ni comme une prestation de travail, ni comme un stage. Cela signifie notamment que le testeur peut mettre un terme à l’immersion à tout moment dès lors que celle-ci ne lui convient pas. En cas de difficultés rencontrées dans le cadre de l’immersion, il vous appartient d’en informer le professionnel et la société METROBOULODODO par écrit exclusivement. Conformément aux stipulations de l’article 5.1 des Conditions Générales d’Utilisation, lorsque l’interruption de l’immersion est faite pour des motifs imputables au professionnel, le testeur est en droit de solliciter le remboursement partiel du prix de l’immersion au prorata du temps effectué.</p>

  <h1>Aide aux professionnels</h1>

  <h3>Que dois-je faire si le testeur est victime d’un accident ou responsable d’un dommage lors de l’immersion ? </h3>
  <p>L’immersion est une prestation de service qui ne s’analyse ni comme une prestation de travail, ni comme un stage. Cela signifie notamment que l’accident dont pourrait être victime le testeur ne s’analyse pas en un accident de travail. Avant d’accueillir le testeur dans le cadre d’une immersion, il vous appartient de vous assurer que ni votre activité professionnelle ni le lieu où se déroulera l’immersion ne constitue un risque pour l’intégrité physique du testeur. Vous vous engagez à accueillir le testeur dans un environnement agréable et exempt de tout danger pour sa personne. Si votre activité professionnelle le justifie, il vous est possible de solliciter du testeur la transmission d’un certificat médical de non contre-indication. En aucun cas la société METROBOULODODO ne saurait être considérée comme garante de l’état de santé du testeur. Avant d’accueillir un testeur, vous avez l’obligation de transmettre à la société METROBOULODODO une attestation d’assurance et de responsabilité civile couvrant les dommages dont vous pourriez être l’auteur ou la victime durant la période d’immersion. En cas d’accident, il vous appartient d’en informer le testeur et votre compagnie d’assurances dans les meilleurs délais afin que celle-ci prenne en charge vos préjudices ou les préjudices que vous avez causés au testeur.</p>

  <h3>Que dois-je faire à l’égard des informations sensibles et/ou confidentielles liées à mon activité professionnelle ? </h3>
  <p>En acceptant d’accueillir le testeur dans le cadre de l’immersion, vous vous engagez à le guider, le conseiller et à l’informer sur les règles, notamment de confidentialité, les codes et la culture de votre société. Vous vous engagez également, en toute bienveillance, à lui transmettre les informations dont il aura besoin. Si vous êtes détenteur d’informations sensibles et/ou confidentielles il est préférable de ne pas les transmettre au testeur ou de vous assurer qu’il n’en fera pas un usage contraire à vos intérêts.</p>

  <h3>Comment articuler l’immersion et la réglementation liée à mon activité professionnelle ?</h3>
  <p>Il vous appartient de veiller au bon respect, par le testeur, de la réglementation et/ou de la déontologie liée à votre activité professionnelle. En aucun cas la société METROBOULODODO ne saurait être tenue responsable en cas de violation, par le testeur, de la réglementation liée à votre activité professionnelle.</p>

  <h3>Quel est le statut de la relation entre le testeur et le professionnel ?</h3>
  <p>L’immersion est une prestation de service qui ne s’analyse ni comme une prestation de travail, ni comme un stage. Cela signifie notamment qu’il n’existe aucun lien de subordination entre le professionnel et le testeur. Il vous appartient de faire respecter les règles de l’entreprise en ce compris ses codes, sa culture, ses horaires et les éventuels équipements. Vous pouvez demander au testeur d’effectuer une tâche non pour lui donner un ordre mais uniquement pour lui permettre d’apprécier le plus concrètement possible votre activité professionnelle. Si cette tâche venait à lui déplaire, vous ne pourrez en aucun cas faire usage d’autorité pour obliger le testeur à l’effectuer.</p>

  <h3>Dois-je rémunérer le testeur pendant l’immersion ?</h3>
  <p>L’immersion est une prestation de service qui ne s’analyse ni comme une prestation de travail, ni comme un stage. Cela signifie notamment que le testeur ne peut prétendre à aucune rémunération, ni à aucune gratification sous quelle qu’en soit la forme. Il vous appartient donc de refuser toute demande de rémunération ou de pourboire qui pourrait être faite durant l’immersion.</p>

  <h3>Est-il possible de refuser un testeur en raison de son apparence physique ou de sa tenue vestimentaire ?</h3>
  <p>Si votre activité professionnelle le justifie, il vous est possible d’exiger du testeur qu’il porte une tenue vestimentaire spécifique. Il vous appartient néanmoins de l’en informer dès la prise de contact et avant la validation de l’immersion. Il vous appartient de veiller à n’opérer aucune discrimination à l’égard du testeur. Il vous est rappelé que conformément aux dispositions de l’article 225-1 du Code pénal, constitue une discrimination « toute distinction opérée entre les personnes physiques à raison de leur origine, de leur sexe, de leur situation de famille, de leur grossesse, de leur apparence physique, de leur patronyme, de leur lieu de résidence, de leur état de santé, de leur handicap, de leurs caractéristiques génétiques, de leurs mœurs, de leur orientation ou identité sexuelle, de leur âge, de leurs opinions politiques, de leurs activités syndicales, de leur appartenance ou de leur non-appartenance, vraie ou supposée, à une ethnie, une nation, une race ou une religion déterminée ».</p>

  <h3>Que dois-je faire si l’immersion ne se déroule pas dans de bonnes conditions ?</h3>
  <p>L’immersion est une prestation de service qui ne s’analyse ni comme une prestation de travail, ni comme un stage. Cela signifie notamment que chaque partie peut mettre un terme à l’immersion à tout moment dès lors que celle-ci ne leur convient pas. La rupture anticipée de l’immersion ne s’analyse ni comme une démission, ni comme un licenciement. En cas de difficultés rencontrées dans le cadre de l’immersion, il vous appartient d’en informer le testeur et la société METROBOULODODO par écrit exclusivement. Conformément aux stipulations de l’article 5.2 des Conditions Générales d’Utilisation, lorsque l’interruption de l’immersion est faite pour des motifs imputables au testeur, l’immersion est considérée comme ayant été effectuée jusqu’à son terme. Au contraire, dans l’hypothèse où les causes de l’interruption ne sont pas imputables au testeur le professionnel ne pourra solliciter aucun versement, même partiel, du prix de l’immersion. Le testeur pourra solliciter le remboursement partiel du prix de l’immersion au prorata du temps effectué.</p>

  <h3>Dois-je déclarer la somme qui m’est versée par la société METROBOULODODO au titre du prix de l’immersion ?</h3>
  <p>Conformément aux stipulations de l’article 3. des conditions générales d’utilisation de la société METROBOULODODO, le règlement du prix de l’immersion ne vous sera versée qu’après réception d’une facture éditée par vos soins. Ainsi, le prix de l’immersion peut être analysé comme un revenu complémentaire. Ce complément de revenu intègre donc votre chiffre d’affaires et doit faire l’objet d’une déclaration auprès de l’administration fiscale. Pour plus de précisions, et dans la mesure où la nature de ce revenu complémentaire est fonction de votre statut professionnel, il est préférable de vous rapprocher de votre cabinet d’experts comptables.</p>

  <h3>Que dois-je faire en cas de contrôle de l’URSSAF durant l’immersion ?</h3>
  <p>A titre liminaire, il convient de rappeler que le testeur n’étant ni un salarié, ni un stagiaire, ni un apprenti il ne fait pas partie du personnel de votre entreprise. En conséquence, en cas de contrôle URSSAF il vous appartiendra d’indiquer à l’inspecteur du recouvrement que le testeur effectue une immersion non assimilable à une activité professionnelle, à un stage ou à un apprentissage. Pour éviter toute difficulté, il vous est conseillé de conclure avec le testeur un contrat stipulant clairement que l’immersion constitue une prestation de service non rémunérée et dépourvue de tout lien de subordination.</p>
</div>
